config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'games#index'

  resources :games, only: [:new, :update, :show, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/Piece.rb
class Piece < ApplicationRecord
  belongs_to :game

  VALID_TYPES = %w[
    Pawn Bishop King Queen Knight Rook 
  ].freeze 

  validates :type, presence: true, inclusion: {in: VALID_TYPES, message: "%{value} is not a valid type"}

  attr_reader :type
  TYPES = [
    # Pieces white side
    :white_rook,
    :white_knight,
    :white_bishop,
    :white_king,
    :white_queen,
    :white_pawn,
    :black_rook,
    :black_knight,
    :black_bishop,
    :black_king,
    :black_queen,
    :black_pawn
  ]
  TYPES_TO_AL = [
    'R',
    'N',
    'B',
    'K',
    'Q',
    'P'
  ]
  # def initialize(t) 
  #   @type = Piece::TYPES.index(t)
  # end
  def self.getTypeMapForJS()
      Piece::TYPES
  end
  def getTypeSym
    return Piece::TYPES[@type]
  end
  def getTypeAl
    ind = @type
    if ind > Piece::TYPES_TO_AL.length - 1
      ind -= Piece::TYPES_TO_AL.length
    end
    return Piece::TYPES_TO_AL[ind]
  end

  def is_obstructed?(destination)

    x1 = cell_x #lets us know where the piece starts
    y1 = cell_y
    x2 = destination.first 
    y2 = destination.last
    del_x = (x2 - x1).positive? ? 1 : -1
    del_y = (y2 - y1).positive? ? 1 : -1
    dest_x = x2 - del_x 
    dest_y = y2 - del_y 


    while x1 != dest_x && y1 != dest_y 
      x1 = del_x + x1 unless x1 == dest_x
      y1 = del_y + y1 unless y1 == dest_y
      return true if Piece.find_by(cell_x: x1, cell_y: y1, game_id: game_id).present?
    end

    return false 

  end

  def valid_move?(x_destination, y_destination) #each piece is going to need to implemnt it's own vaild move method 
    raise NotImplementedError 
  end

end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bishop.rb
class Bishop < Piece

def valid_move?(x_destination, y_destination)
  ((cell_y - y_destination) / (cell_x - x_destination)).abs == 1 && 
  (cell_y - y_destination).abs <= 7 && 
  (cell_x - x_destination).abs <= 7 && 
  is_obstructed([x_destination, y_destination])
end

end

app/models/game.rb
class Game < ApplicationRecord
  scope :available, -> { where("user_id_white = null") }
 
  has_many :pieces

  belongs_to :user_id_white, class_name: 'User', foreign_key: 'user_id_white'
  belongs_to :user_id_black, class_name: 'User', foreign_key: 'user_id_black'
  
  def getBoardObject
    return [
      [6,7,8,9,10,8,7,6],
      [11,11,11,11,11,11,11,11],
      [-1,-1,-1,-1,-1,-1,-1,-1],
      [-1,-1,-1,-1,-1,-1,-1,-1],
      [-1,-1,-1,-1,-1,-1,-1,-1],
      [-1,-1,-1,-1,-1,-1,-1,-1],
      [5,5,5,5,5,5,5,5],
      [0,1,2,4,3,2,1,0],
    ]
  end
  
end

app/models/king.rb
class King < Piece

  def valid_move?(x_destination, y_destination)
    return false unless is_obstructed?([x_destination, y_destination])

    (cell_x - x_destination).abs <= 1 && (cell_y - y_destination).abs <= 1  

  end

end

app/models/knight.rb
class Knight < Piece

  def valid_move?(destination_x, destination_y)
    delta_x = (cell_x - destination_x).abs 
    delta_y = (cell_y - destination_y).abs 

    (delta_x == 2 && delta_y == 1) || (delta_x == 1 && delta_y == 2)
  end 

end

app/models/pawn.rb
class Pawn < Piece

def valid_move?(x_destination, y_destination)
  return false if is_obstructed([x_destination, y_destination])
  if [2,7].include?(cell_y)
   (cell_x - x_destination).abs == 0 && (cell_y - y_destination).abs <= 2
  else 
    (cell_x - x_destination).abs == 0 && (cell_y - y_destination).abs == 1

end

app/models/piece.rb
class Piece < ApplicationRecord
  belongs_to :game

  attr_reader :type
  TYPES = [
    # Pieces white side
    :white_rook,
    :white_knight,
    :white_bishop,
    :white_king,
    :white_queen,
    :white_pawn,
    :black_rook,
    :black_knight,
    :black_bishop,
    :black_king,
    :black_queen,
    :black_pawn
  ]
  TYPES_TO_AL = [
    'R',
    'N',
    'B',
    'K',
    'Q',
    'P'
  ]
  def initialize(t) 
    @type = Piece::TYPES.index(t)
  end
  def getTypeSym
    return Piece::TYPES[@type]
  end
  def getTypeAl
    ind = @type
    if ind > Piece::TYPES_TO_AL.length - 1
      ind -= Piece::TYPES_TO_AL.length
    end
    return Piece::TYPES_TO_AL[ind]
  end

  def is_obstructed?(destination)

    x1 = self.cell_x #lets us know where the piece starts
    y1 = self.cell_y
    x2 = destination.first 
    y2 = destination.last
    del_x = (x2 - x1).positive? ? 1 : -1
    del_y = (y2 - y1).positive? ? 1 : -1
    dest_x = x2 - del_x 
    dest_y = y2 - del_y 


    while x1 != dest_x && y1 != dest_y 
      x1 = del_x + x1 unless x1 == dest_x
      y1 = del_y + y1 unless y1 == dest_y
      return true if Piece.find_by(cell_x: x1, cell_y: y1, game_id: game_id).present?
    end

    return false 

  end

end 

app/models/queen.rb
class Queen < Piece
	
	def valid_move?(x_destination, y_destination)
		cell_x == x_destination || cell_y == y_destination ||
		(cell_x - x_destination).abs == (cell_y - y_destination).abs
  	end

end

app/models/rook.rb
class Rook < Piece

    def valid_move?(x_destination, y_destination)
        ((cell_x - x_destination).abs >= 1 && cell_x - x_destination).abs <= 8) && 
        (cell_y - y_destination).zero? && 
        is_obstructed?([x_destination, y_destination]) ||
        ((cell_y - y_destination).abs >= 1 && cell_y - y_destination).abs <= 8) && 
        (cell_x - x_destination).zero? && 
        is_obstructed?([x_destination, y_destination])
    end    

end

app/models/user.rb
class User < ApplicationRecord
  has_many :games
  has_many :pieces
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @games = Game.all
  end

  def new 
    @game = Game.new
  end

  def create
    @game = Game.create(game_params)
  end

  def update
    @game = Game.find(params[:id])
    if current_user 
      @game.update(user_id_white: current_user.id)     
    redirect_to game_path
    end
   end

  def show
    begin 
      @game = Game.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @game = Game.new
      @game.user_id = current_user.id
      @game.save
    end
  end
  
  private

  def game_params
    params.require(:game).permit(:name, :user_id_black)
  end
  
  def available
    if white_player_id
      return true
    else
      return false
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-light">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Chess Game App</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
	  <% if user_signed_in? %>  
      <li class="nav-item">
        <%= link_to 'Player', '#', class: 'nav-link' %>
      </li>
        <% else %>
      <li class="nav-item">
        <%= link_to 'Sign-In', '#', class: 'nav-link' %>
      </li>
        <% end %>
      <li class="nav-item">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>


<span>
	<% Game.available.each do |game| %>
	  <tr class="game-table-row">
	    <td ><%= game.name %></td>
	    <td><%= game.user_id_black %></td>
	    <td><%= link_to 'Join', game_path(game.id), method: :patch %></td>
	  </tr>
	<% end %>
</span>

app/views/games/new.html.erb
<h1>Game Name</h1>
<%= simple_form_for @game, url: games_path do |f| %>
  
  <br />
  <%= f.submit "Create", class: 'btn btn-primary' %>
<% end %>

app/views/games/show.html.erb
<div class="chess-board" data-width="480" data-black="#333">

</div>
<script type="text/javascript">
  let game =  create_chess_board($('div.chess-board'),<%= @game.id %>, <%= @game.getBoardObject.to_json %>);
  window.TYPES = <%= Piece::getTypeMapForJS().to_json.html_safe %>;
  game();
  $('body').on('chess-render-board',game);
</script>


app/views/layouts/_board.html.erb
<div class="chess-board" data-width="640" data-black="#333">

</div>
<script type="text/javascript">
  create_chess_board('div.chess-board');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chess</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
      <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>